
stages:
  - ci
  - cd
  - cleanup
  - release

variables:
  PYTHON_VERSION: "3.11"
  IMAGE_BASE: python:${PYTHON_VERSION}-slim-bullseye


.validate_input: &validate_input
  - |
    if [[ $ADMIN_TOKEN =~ .*ADMIN_TOKEN ]]; then
      echo "Set ADMIN_TOKEN variable"; exit 1;
    fi

.run_ci:
  stage: ci
  image: ${IMAGE_BASE}
  interruptible: true
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git
  script:
    - *validate_input
    - _ENV_FLAGS="${ENV_FLAGS:=--last-partition --wait}"
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR
    - _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')
    - source .tinyenv

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Check all the data files syntax
    - tb check

    # Create new test Environment with data
    - |
      tb \
        --host $TB_HOST \
        --token $ADMIN_TOKEN \
        env create tmp_ci_${_NORMALIZED_ENV_NAME}_${CI_COMMIT_SHORT_SHA} \
        ${_ENV_FLAGS}

    # List changes with Main Environment
    - tb diff --main --no-verbose

    # Push changes to the test Environment
    - |
      CI_DEPLOY_FILE=./deploy/${VERSION}/ci-deploy.sh
      if [ -f "$CI_DEPLOY_FILE" ]; then
        ./deploy/${VERSION}/ci-deploy.sh
      else
        tb deploy --populate --fixtures --wait
      fi

    # List changes with test Environment (should be empty)
    - tb diff

    - |
      if [ -f ./scripts/exec_test.sh ]; then
        ./scripts/exec_test.sh
      fi

    # Run data quality tests
    - tb test run -v

    # Run pipe regression tests
    - echo ${CI_MERGE_REQUEST_LABELS}
    - REGRESSION_LABELS=$(echo "${CI_MERGE_REQUEST_LABELS}" | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /^--/) print $i}' ORS=',' | sed 's/,$//')
    - echo ${REGRESSION_LABELS}
    - tb env regression-tests coverage --wait $(echo ${REGRESSION_LABELS} | tr , ' ')

.run_cd:
  stage: cd
  image: ${IMAGE_BASE}
  interruptible: true
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git
  script:
    - *validate_input
    - _ENV_FLAGS="${ENV_FLAGS:=--last-partition --wait}"
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR
    - _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')
    - source .tinyenv

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Check all the data files syntax
    - tb check

    # Create new test Environment with data
    - |
      tb \
        --host $TB_HOST \
        --token $ADMIN_TOKEN \
        env create tmp_cd_${_NORMALIZED_ENV_NAME}_${CI_COMMIT_SHORT_SHA} \
        ${_ENV_FLAGS}

    # List changes with Main Environment
    - tb diff --main --no-verbose

    # Push changes to the test Environment
    - |
      CI_DEPLOY_FILE=./deploy/${VERSION}/ci-deploy.sh
      if [ -f "$CI_DEPLOY_FILE" ]; then
        ./deploy/${VERSION}/ci-deploy.sh
      else
        tb deploy --populate --fixtures --wait
      fi

    # List changes with test Environment (should be empty)
    - tb diff

    # Deploy changes to the main Workspace
    - |
      if [ "$TB_DEPLOY" = "true" ]; then
        tb env deploy --semver ${VERSION} --wait
        tb release ls
      else
        CD_DEPLOY_FILE=./deploy/${VERSION}/cd-deploy.sh
        if [ ! -f "$CD_DEPLOY_FILE" ]; then
          tb auth \
            --host $TB_HOST \
            --token $ADMIN_TOKEN
          tb deploy
        fi
      fi

    # OPTIONALLY run post CD deploy commands (e.g.: tb pipe populate)
    - |
      CD_DEPLOY_FILE=./deploy/${VERSION}/cd-deploy.sh
      if [ -f "$CD_DEPLOY_FILE" ]; then
        ./deploy/${VERSION}/cd-deploy.sh
      fi

.cleanup_ci_branch:
  stage: cleanup
  image: ${IMAGE_BASE}
  script:
    - *validate_input
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR
    - _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Remove test Environment
    - |
      tb \
      --host $TB_HOST \
      --token $ADMIN_TOKEN \
      env rm tmp_ci_${_NORMALIZED_ENV_NAME}_${CI_COMMIT_SHORT_SHA} \
      --yes

.cleanup_cd_branch:
  stage: cleanup
  image: ${IMAGE_BASE}
  script:
    - *validate_input
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR
    - _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Remove Environment
    - |
      tb \
      --host $TB_HOST \
      --token $ADMIN_TOKEN \
      env rm tmp_cd_${_NORMALIZED_ENV_NAME}_${CI_COMMIT_SHORT_SHA} \
      --yes

.release_promote:
  stage: release
  image: ${IMAGE_BASE}
  script:
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Promote Release
    - |
      source .tinyenv
      tb release promote \
      --host $TB_HOST \
      --token $ADMIN_TOKEN \
      --semver $VERSION

.release_rollback:
  stage: release
  image: ${IMAGE_BASE}
  script:
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Promote Release
    - |
      source .tinyenv
      tb release rollback \
      --host $TB_HOST \
      --token $ADMIN_TOKEN

.release_rm:
  stage: release
  image: ${IMAGE_BASE}
  script:
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Promote Release
    - |
      source .tinyenv
      tb release rm --semver $VERSION \
      --host $TB_HOST \
      --token $ADMIN_TOKEN
