
name: Tinybird CI

on:
  workflow_call:
    inputs:
      tb_deploy:
        description: "use tb deploy based on git releases"
        required: false
        type: boolean
        default: false
      data_project_dir:
        description: "relative path of the folder containing the data project"
        required: false
        type: string
        default: .
    secrets:
      tb_admin_token:
        required: true
      tb_host:
        required: true

jobs:
  environment:
    name: Create CI Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.data_project_dir }}
    if: ${{ github.event.action != 'closed' }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 300
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Validate input
        run: |
          [[ "${{ secrets.tb_admin_token }}" ]] || { echo "Go to the tokens section in your Workspace, copy the 'admin token (user@domain.com)' associated to a user account and set TB_ADMIN_TOKEN as a Secret in your Git repository"; exit 1; }

      - name: Set environment variables
        run: |
          _ENV_FLAGS="${ENV_FLAGS:=--last-partition --wait}"
          _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')
          GIT_BRANCH=${GITHUB_HEAD_REF}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "_ENV_FLAGS=$_ENV_FLAGS" >> $GITHUB_ENV
          echo "_NORMALIZED_ENV_NAME=$_NORMALIZED_ENV_NAME" >> $GITHUB_ENV
          cat .tinyenv >> $GITHUB_ENV
          echo >> $GITHUB_ENV # Ensures new line at the end of the file

      - name: Install Tinybird CLI
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            pip install tinybird-cli
          fi

      - name: Tinybird version
        run: tb --version

      - name: Check all the data files syntax
        run: tb check  

      - name: Check auth
        run: tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} auth info

      - name: Try delete previous Environment
        run: |
          output=$(tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} env ls)
          ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }}"

          # Check if the environment name exists in the output
          if echo "$output" | grep -q "\b$ENVIRONMENT_NAME\b"; then
              tb \
                --host ${{ secrets.tb_host }} \
                --token ${{ secrets.tb_admin_token }} \
                env rm $ENVIRONMENT_NAME \
                --yes
          else
              echo "Skipping clean up: The Environment '$ENVIRONMENT_NAME' does not exist."
          fi

      - name: Create new test Environment with data
        run: |
          tb \
          --host ${{ secrets.tb_host }} \
          --token ${{ secrets.tb_admin_token }} \
          env create tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }} \
          ${_ENV_FLAGS}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - environment
    defaults:
      run:
        working-directory: ${{ inputs.data_project_dir }}
    if: ${{ github.event.action != 'closed' }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 300
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Validate input
        run: |
          [[ "${{ secrets.tb_admin_token }}" ]] || { echo "Go to the tokens section in your Workspace, copy the 'admin token (user@domain.com)' associated to a user account and set TB_ADMIN_TOKEN as a Secret in your Git repository"; exit 1; }

      - name: Set environment variables
        run: |
          _ENV_FLAGS="${ENV_FLAGS:=--last-partition --wait}"
          _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')
          GIT_BRANCH=${GITHUB_HEAD_REF}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "_ENV_FLAGS=$_ENV_FLAGS" >> $GITHUB_ENV
          echo "_NORMALIZED_ENV_NAME=$_NORMALIZED_ENV_NAME" >> $GITHUB_ENV
          cat .tinyenv >> $GITHUB_ENV
          echo >> $GITHUB_ENV # Ensures new line at the end of the file

      - name: Install Tinybird CLI
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            pip install tinybird-cli
          fi

      - name: Tinybird version
        run: tb --version

      - name: Check auth
        run: tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} auth info

      - name: Use Environment
        run: |
          ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }}"
          tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} env use $ENVIRONMENT_NAME

      - name: Get regression labels
        id: regression_labels
        uses: SamirMarin/get-labels-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label_key: regression

      - name: Deployment
        run: |
            source .tinyenv
            DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
            if [ ! -f "$DEPLOY_FILE" ]; then
              if ${{ inputs.tb_deploy }}; then
                REGRESSION_LABELS=$(echo "${{ steps.regression_labels.outputs.labels }}")
                if echo "--force" | grep -q "\b$REGRESSION_LABELS\b"; then
                  tb --semver ${VERSION} deploy --v3 ${CI_FLAGS} --force
                else
                  tb --semver ${VERSION} deploy --v3 ${CI_FLAGS}
                fi
                tb release ls
              else
                tb deploy --populate --fixtures --wait
              fi
            fi

      - name: Custom deployment
        run: |
            source .tinyenv
            DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
            if [ -f "$DEPLOY_FILE" ]; then
              if ! [ -x "$DEPLOY_FILE" ]; then
                echo "Error: You do not have permission to execute '$DEPLOY_FILE'. Run:"
                echo "> chmod +x $DEPLOY_FILE"
                echo "and commit your changes"
                exit 1
              else
                $DEPLOY_FILE
              fi
            fi

  test:
    runs-on: ubuntu-latest
    needs:
      - deploy
    defaults:
      run:
        working-directory: ${{ inputs.data_project_dir }}
    if: ${{ github.event.action != 'closed' }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 300
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Validate input
        run: |
          [[ "${{ secrets.tb_admin_token }}" ]] || { echo "Go to the tokens section in your Workspace, copy the 'admin token (user@domain.com)' associated to a user account and set TB_ADMIN_TOKEN as a Secret in your Git repository"; exit 1; }

      - name: Set environment variables
        run: |
          _ENV_FLAGS="${ENV_FLAGS:=--last-partition --wait}"
          _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')
          GIT_BRANCH=${GITHUB_HEAD_REF}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "_ENV_FLAGS=$_ENV_FLAGS" >> $GITHUB_ENV
          echo "_NORMALIZED_ENV_NAME=$_NORMALIZED_ENV_NAME" >> $GITHUB_ENV
          cat .tinyenv >> $GITHUB_ENV
          echo >> $GITHUB_ENV # Ensures new line at the end of the file

      - name: Install Tinybird CLI
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            pip install tinybird-cli
          fi

      - name: Tinybird version
        run: tb --version

      - name: Check auth
        run: tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} auth info

      - name: Use Environment
        run: |
          ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }}"
          tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} env use $ENVIRONMENT_NAME

      - name: Run fixture tests
        run: |
          if [ -f ./scripts/exec_test.sh ]; then
            ./scripts/exec_test.sh
          fi

      - name: Run data quality tests
        run: |
          tb test run -v -c 4

      - name: Get regression labels
        id: regression_labels
        uses: SamirMarin/get-labels-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label_key: regression

      - name: Run pipe regression tests
        run: |
          source .tinyenv
          echo ${{ steps.regression_labels.outputs.labels }}
          REGRESSION_LABELS=$(echo "${{ steps.regression_labels.outputs.labels }}" | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /^--/) print $i}' ORS=',' | sed 's/,$//')
          echo ${REGRESSION_LABELS}

          CONFIG_FILE=./tests/regression.yaml
          BASE_CMD="tb env regression-tests"
          LABELS_CMD="$(echo ${REGRESSION_LABELS} | tr , ' ')"
          if [ -f ${CONFIG_FILE} ]; then
              echo "Config file found: ${CONFIG_FILE}"
              ${BASE_CMD} -f ${CONFIG_FILE} --wait ${LABELS_CMD}
          else
              echo "Config file not found at '${CONFIG_FILE}', running with default values"
              ${BASE_CMD} coverage --wait ${LABELS_CMD}
          fi

  cleanup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.data_project_dir }}
    if: ${{ github.event.action == 'closed' }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Validate input
        run: |
          [[ "${{ secrets.tb_admin_token }}" ]] || { echo "Go to the tokens section in your Workspace, copy the 'admin token (user@domain.com)' associated to a user account and set TB_ADMIN_TOKEN as a Secret in your Git repository"; exit 1; }

      - name: Install Tinybird CLI
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            pip install tinybird-cli
          fi

      - name: Tinybird version
        run: tb --version

      - name: Try delete previous Environment
        run: |
          output=$(tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} env ls)
          ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }}"

          # Check if the environment name exists in the output
          if echo "$output" | grep -q "\b$ENVIRONMENT_NAME\b"; then
              tb \
                --host ${{ secrets.tb_host }} \
                --token ${{ secrets.tb_admin_token }} \
                env rm $ENVIRONMENT_NAME \
                --yes
          else
              echo "Skipping clean up: The Environment '$ENVIRONMENT_NAME' does not exist."
          fi
